from pathlib import Path

from src.services.scanner.context_extractor import ContextExtractor
from src.services.scanner.types import RawFinding


def test_extract_basic_context(tmp_path: Path) -> None:
    content = "\n".join(
        [
            "# Generated by test harness",
            "import os",
            "",
            "class MyClass:",
            "    def target(self):",
            "        return os.getenv('X')",
        ]
    )
    file_path = tmp_path / "app.py"
    file_path.write_text(content, encoding="utf-8")

    finding = RawFinding(
        rule_id="rule-1",
        rule_message="msg",
        severity="ERROR",
        file_path="app.py",
        line_start=5,
        line_end=5,
        code_snippet="return os.getenv('X')",
    )

    extractor = ContextExtractor(enable_reachability=False)
    context = extractor.extract(tmp_path, finding, context_lines=1)

    assert "def target" in context.snippet
    assert context.function_name == "target"
    assert context.class_name == "MyClass"
    assert context.is_generated is True
    assert context.is_test_file is False
    assert "import os" in context.imports


def test_extract_missing_file_returns_empty_context(tmp_path: Path) -> None:
    finding = RawFinding(
        rule_id="rule-1",
        rule_message="msg",
        severity="ERROR",
        file_path="tests/test_missing.py",
        line_start=10,
        line_end=10,
        code_snippet="pass",
    )

    extractor = ContextExtractor(enable_reachability=False)
    context = extractor.extract(tmp_path, finding)

    assert context.snippet == ""
    assert context.is_test_file is True
    assert context.imports == []
